
"""Tool functions for the Movie Watchlist MCP server."""

import os
from pydantic import BaseModel, Field
from mcp.server.fastmcp import Context
from mcp.types import SamplingMessage, TextContent
from mcp_server_watchlist.resources import get_all_movies
from mcp_server_watchlist import db


def _is_sampling_enabled() -> bool:
    """Read runtime flag to decide whether LLM sampling should be attempted."""
    raw = os.environ.get("ENABLE_LLM_SAMPLING", "true").strip().lower()
    return raw in {"1", "true", "yes", "y", "on"}


def _is_elicitation_enabled() -> bool:
    """Read runtime flag to decide whether elicitation should be attempted."""
    raw = os.environ.get("ENABLE_ELICITATION", "true").strip().lower()
    return raw in {"1", "true", "yes", "y", "on"}


def _build_watchlist_overview(movies: list[str]) -> str:
    """Build watchlist response without using LLM sampling."""
    movie_lines = "\n".join(f"- {movie}" for movie in movies)

    return (
        "[Watchlist Summary]\n\n"
        "Sampling is disabled or unavailable. Here is your watchlist:\n"
        f"{movie_lines}"
    )


async def show_watchlist() -> list[str]:
    """Return the current watchlist as a plain list of formatted movie entries."""
    return await get_all_movies()

async def summarize_watchlist(ctx: Context) -> str:
    """
    Summarize the user's watchlist using LLM sampling.
    The summary is generated by sending the list of movies to the LLM and asking for a friendly summary.
    """
    movies = await get_all_movies()
    if not movies:
        return "Your watchlist is empty. Add some movies to get a summary!"

    if not _is_sampling_enabled():
        return _build_watchlist_overview(movies)

    movie_list = '\n'.join(movies)
    prompt = (
        "Here is a user's movie watchlist. "
        "Write a friendly summary or insight about their watchlist. "
        "You may mention genres, years, or trends if you notice any.\n\n"
        f"Watchlist:\n{movie_list}"
    )
    # Use LLM sampling
    message_result = await ctx.session.create_message(
        messages=[
            SamplingMessage(
                role="user",
                content=TextContent(type="text", text=prompt),
            )
        ],
        system_prompt="You are a helpful movie assistant.",
        max_tokens=100,
    )
    if message_result.content.type == "text":
        return (
            f"[Watchlist Summary]\n\n"
            f"{message_result.content.text}"
        )
    return (
        f"[Watchlist Summary]\n\n"
        f"{str(message_result.content)}"
    )

class RatingInput(BaseModel):
    """Schema for collecting rating input from user."""
    rating: float = Field(description="Rate the movie out of 10")

async def add_movie(title: str, year: int) -> str:
    """
    Add a movie to the watchlist.
    Args:
        title: Movie name (exclude year)
        year: Year of release
    """
    await db.execute(
        "INSERT INTO watchlist (title, year) VALUES (:title, :year)",
        {"title": title, "year": year},
    )
    # New movies have no rating by default
    return (
        f"Added: Title: {title}, Year: {year}, "
        f"Rating: N/A to watchlist."
    )

async def mark_watched(title: str, ctx: Context | None = None) -> str:
    """
    Mark a movie as watched using title-only input.

    Rating is collected only through MCP elicitation when enabled.
    This tool never accepts rating as a direct input argument.

    Args:
        title: Movie name (exclude year)

    Note:
        Pass only the movie name, not including the year. If the year is present,
        remove it before calling.
    """
    row = await db.fetch_one(
        "SELECT year FROM watchlist WHERE title = :title",
        {"title": title},
    )
    if not row:
        return f"Movie not found in watchlist: Title: {title}"
    rating = None
    if _is_elicitation_enabled() and ctx is not None:
        # Use elicitation to get rating input from user.
        result = await ctx.elicit(
            message="Great! Please provide your rating.",
            schema=RatingInput,
        )
        if getattr(result, "action", None) == "accept" and getattr(result, "data", None):
            accepted_rating = getattr(result.data, "rating", None)
            if accepted_rating is not None:
                rating = accepted_rating
    await db.execute(
        "UPDATE watchlist SET watched = 1, rating = :rating WHERE title = :title",
        {"rating": rating, "title": title},
    )
    year = row[0]
    return (
        f"Marked as watched: Title: {title}, Year: {year}, "
        f"Rating: {rating if rating is not None else 'N/A'}"
    )

async def unwatch_movie(title: str) -> str:
    """
    Mark a movie as unwatched.
    Args:
        title: Movie name (exclude year)
    Note:
        Pass only the movie name, not including the year. If the year is present, remove it before calling.
    """
    row = await db.fetch_one(
        "SELECT year, rating FROM watchlist WHERE title = :title",
        {"title": title},
    )
    if not row:
        return f"Movie not found in watchlist: Title: {title}"
    await db.execute(
        "UPDATE watchlist SET watched = 0, rating = NULL WHERE title = :title",
        {"title": title},
    )
    year = row[0]
    rating = row[1] if row[1] is not None else 'N/A'
    return (
        f"Marked as unwatched: Title: {title}, Year: {year}, "
        f"Rating: {rating}"
    )

async def delete_movie(title: str) -> str:
    """
    Delete a movie from the watchlist.
    Args:
        title: Movie name (exclude year)
    Note:
        Pass only the movie name, not including the year. If the year is present, remove it before calling.
    """
    row = await db.fetch_one(
        "SELECT year, rating FROM watchlist WHERE title = :title",
        {"title": title},
    )
    if not row:
        return f"Movie not found in watchlist: Title: {title}"
    await db.execute(
        "DELETE FROM watchlist WHERE title = :title",
        {"title": title},
    )
    year = row[0]
    rating = row[1] if row[1] is not None else 'N/A'
    return (
        f"Deleted: Title: {title}, Year: {year}, "
        f"Rating: {rating} from watchlist."
    )
